# Generated by Django 4.2.4 on 2023-10-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.TextField(default=' ', help_text='Enter Name of the Color', max_length=250),
        ),
    ]
