# Generated by Django 4.2.7 on 2023-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_invoice_invoice_number_alter_invoice_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.TextField(default='none', help_text='Enter the Size', max_length=250, null=True),
        ),
    ]
